--- 
data:
  data_location: data/noshow.db
  data_table: noshow
preprocess:
  int_cols: ["num_adults", "arrival_day", "checkout_day", "num_children"]
  bins: 5
  encode: "ordinal"
  strategy: "uniform"
  exchange: 1.3439
feature_eng:
  ohe1: ["branch", "first_time", "platform"]
  ore1: ["country"]
  sim1: ["SGD_price"]
  ore2: ["branch", "country", "first_time", "platform"]
  sim2: ["SGD_price"]
  strategy: "mean"
mlpipeline:
  dependent_y: no_show
  drop: ["booking_id", "booking_month", "arrival_month", "arrival_day", "checkout_month", "checkout_day" , "price", "num_adults", "num_children", "currency", "room"]
  results: True
  class_report: False
  lr:
    name: "Logistic Regression Classifier"
    params:
      penalty: "l1"
      solver: "liblinear"
      max_iter: 50
      c: 0.1
  dt:
    name: "Decision Tree Classifier"
    params:
      max_depth: 5
      min_samples_split: 3
      min_samples_leaf: 10
      criterion: 'log_loss'
      splitter: 'best'
  rf:
    name: "Random Forest Classifier"
    params:
      n_estimators: 600
      criterion: "log_loss"
      max_depth: 15
      min_samples_split: 50
      min_samples_leaf: 100
      max_leaf_nodes: 40
      max_features: 

