name: hotel-bookings
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          
# Testing CI workflows
  linting:
    runs-on: ubuntu-latest
    needs: ["build"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install pylint
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint
      - name: Lint pylint
        run: |
          export PYTHONPATH=${PWD}
          pylint --fail-under=8 ${PWD}/src ${PWD}/tests
  unit-test:
    runs-on: ubuntu-latest
    needs: ["linting"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run unit test
        run: |
          python -m pytest -vv
          
# Deployment
  deployment:
    runs-on: ubuntu-latest
    needs: ["unit-test"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run executable bash script
        run: |
          echo "Not yet deployed"

