name: AIAP Assessment 2
on: [push, workflow_dispatch]

jobs:
  run-end-to-end-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run executable bash script
        run: bash ./run.sh
      - name: Assessment 2 Reminder
        run: |
          echo "Reminder to add AISG-AIAP as a collaborator in your repository"
          echo "Once your submission is complete, fill up the form provided in the Assessment 2 document"
# Additional CI workflows
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install pylint
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint
      - name: Lint pylint
        run: |
          export PYTHONPATH=${PWD}
          pylint --fail-under=8 ${PWD}/src ${PWD}/tests
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run unit test
        run: |
          python -m pytest -vv
